spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1q2w3e4r!

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      show-sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
